### ISSUE TITLE
Disable Effects In Lobby setting keeps resetting at every game restart

### ISSUE THREAD

**Issue by CapoFantasma97** [hatwearingdumb/dof.and.bloom.remover#1]
Via Northstar's Mod Settings, I set the DoF in Lobby to be disabled (Yes).

It works fine, until I close the game. The next time I launch the game, it's reset (No) and the DoF effect shows up again in the lobby.

**Comment by hatwearingdumb** [comment]
I have no idea how I never read this. I'll try to look into it this weekend. Sorry!
